name: codex_vault
description: A Flutter desktop application for managing ChatGPT conversation history.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.7
  intl: ^0.18.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
